name: Publish to Maven Central

on:
  push:
    branches:
      - main
      - 'test-publish/*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.SIGNING_KEY_SECRET_ARMOR_EXPORT }}") | gpg --batch --import

      - name: List gpg secret keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Export gpg secret key
        run: sudo gpg --export-secret-keys --pinentry-mode loopback --passphrase=${{ secrets.SIGNING_KEY_PASSWORD }} ${{ secrets.SIGNING_KEY_ID }} > ${{ secrets.SIGNING_KEY_LOCATION }}

      - name: Check dir
        run: ls .gnupg

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_LOCATION: ${{ secrets.SIGNING_KEY_LOCATION }}
